name=OptaEtherNetIP
version=0.1.0
maintainer=Arduino Opta OpENer
sentence=EtherNet/IP adapter library for Arduino Opta using OpENer and Mbed Ethernet.
paragraph=Initial library packaging of the tested Opta OpENer Ethernet implementation.
category=Communication
architectures=mbed_opta
includes=opener_api.h
